---
# Infrastructure Applications
# This configures all infrastructure components (controllers, operators, etc.)

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./infrastructure"
  prune: true
  wait: true
  timeout: 5m0s
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
    - apiVersion: apps/v1
      kind: Deployment
      name: ingress-nginx-controller
      namespace: ingress-nginx
  patches:
    - patch: |
        - op: replace
          path: /spec/values/controller/service/annotations
          value:
            oci.oraclecloud.com/load-balancer-type: "nlb"
      target:
        kind: HelmRelease
        name: ingress-nginx
