---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
    toolkit.fluxcd.io/tenant: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
    toolkit.fluxcd.io/tenant: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    toolkit.fluxcd.io/tenant: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: dylanmtaylor
  labels:
    name: dylanmtaylor
    toolkit.fluxcd.io/tenant: applications
